# DNS: <service-name>.prod.svc.cluster.local
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: production
    spec:
    # Add a list of the development containers we need present
    # Reminder example below (would need to create in ECR)
      containers:
      - name: prod-account-services     # TODO: CREATE PROD CONTAINERS IN ECR
        image: account-services:latest  # TODO: REWRITE TO MATCH AWS PROD CONTAINERS
        ports:
        - containerPort: 80             # TODO: REWRITE TO MATCH ACTUAL PORTS
      - name: prod-auth-services
        image: auth-services:latest
        ports:
        - containerPort: 81
      - name: prod-budget-services
        image: budget-services:latest
        ports:
        - containerPort: 82
      - name: prod-credit-score-service
        image: credit-score-service:latest
        ports:
        - containerPort: 83
      - name: prod-discovery-service
        image: discovery-service:latest
        ports:
        - containerPort: 84
      - name: prod-gateway-service
        image: gateway-service:latest
        ports:
        - containerPort: 85
      - name: prod-tax-service
        image: tax-service:latest
        ports:
        - containerPort: 86
      - name: prod-transaction-service
        image: transaction-service:latest
        ports:
        - containerPort: 87
      - name: prod-user-service
        image: user-service:latest
        ports:
        - containerPort: 88
