apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: prod
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "256Mi"
      type: Container
