apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: staging
spec:
  limits:
    - default:
        cpu: "1"
        memory: "768Mi"
      defaultRequest:
        cpu: "500m"
        memory: "768Mi"
      type: Container
