apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DATABASE_USERNAME: <postgres-user>
  DATABASE_PASSWORD: <postgres-password>
  EUREKA_URL: http://eureka:8761/eureka
