# h/t heyvaldemar/aws-kubectl
FROM 924809052459.dkr.ecr.us-east-1.amazonaws.com/aws-kubectl:latest

RUN apt-get update && apt-get install -y \
  python3 \
  python3-venv \
  python3-pip \
  openjdk-11-jdk \
  && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --upgrade pip \
  && pip install virtualenv \
  && pip install bzt

RUN python3 -m venv /opt/venv
