apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget
  template:
    metadata:
      name: budget
      labels:
        app: budget
    spec:
      serviceAccountName: budget
      containers:
        - name: budget
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/budget-services:latest
          ports:
            - containerPort: 8082
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://db:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
