apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8125
      targetPort: 8125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      serviceAccountName: gateway-service
      containers:
        - name: gateway-service
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/gateway-service:<image-version>
          imagePullPolicy: Always
          ports:
            - containerPort: 8125
              name: http
          env:
            - name: AWS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FRONTEND_URL
              value: https://frontend.skillstorm-congo.com/
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: DATABASE_URL
              value: <database-url>

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
