apiVersion: v1
kind: Service
metadata:
  name: auth-services
spec:
  selector:
    app: auth-services
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-services
  template:
    metadata:
      name: auth-services
      labels:
        app: auth-services
    spec:
      serviceAccountName: auth-services
      containers:
        - name: auth-services
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/auth-services:<image-version>
          ports:
            - containerPort: 8888
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres.staging.svc.cluster.local:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
