apiVersion: v1
kind: Service
metadata:
  name: credit-score-service
spec:
  selector:
    app: credit-score-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: credit-score-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-score-service
  template:
    metadata:
      name: credit-score-service
      labels:
        app: credit-score-service
    spec:
      serviceAccountName: credit-score-service
      containers:
        - name: credit-score-service
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/credit-score-service:<image-version>
          ports:
            - containerPort: 8085
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres.staging.svc.cluster.local:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
