apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8125
      targetPort: 8125
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      serviceAccountName: gateway-service
      containers:
        - name: gateway-service
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/gateway-service:<image-version>
          ports:
            - containerPort: 8125
              name: http
          resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
          env:
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres.staging.svc.cluster.local:5432/my_budget_buddy
            - name: EUREKA_URL
              value: <eureka-url>

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
