apiVersion: v1
kind: Service
metadata:
  name: budget-services
spec:
  selector:
    app: budget-services
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: budget-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-services
  template:
    metadata:
      name: budget-services
      labels:
        app: budget-services
    spec:
      serviceAccountName: budget-services
      containers:
        - name: budget-services
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/budget-services:latest
          ports:
            - containerPort: 8082
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://db:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: budget-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: budget-secret
                  key: POSTGRES_PASSWORD
