apiVersion: v1
kind: Service
metadata:
  name: account-services
spec:
  selector:
    app: account-services
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-services
  template:
    metadata:
      name: account-services
      labels:
        app: account-services
    spec:
      serviceAccountName: account
      containers:
        - name: account-services
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/account-services:<image-version>
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres.staging.svc.cluster.local:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
