apiVersion: v1
kind: Service
metadata:
  name: transaction
spec:
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction
  template:
    metadata:
      name: transaction
      labels:
        app: transaction
    spec:
      serviceAccountName: transaction
      containers:
        - name: transaction
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/transaction-service:latest
          ports:
            - containerPort: 8083
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres.staging.svc.cluster.local:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
