apiVersion: v1
kind: Service
metadata:
  name: tax-service
spec:
  selector:
    app: tax-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tax-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-service
  template:
    metadata:
      name: tax-service
      labels:
        app: tax-service
    spec:
      serviceAccountName: tax-service
      containers:
        - name: tax-service
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/tax-service:latest
          ports:
            - containerPort: 8084
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: jdbc:postgresql://db:5432/my_budget_buddy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: tax-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tax-secret
                  key: POSTGRES_PASSWORD
