apiVersion: v1
kind: Service
metadata:
  name: budget-services
spec:
  selector:
    app: budget-services
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: budget-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-services
  template:
    metadata:
      name: budget-services
      labels:
        app: budget-services
    spec:
      serviceAccountName: budget-services
      containers:
        - name: budget-services
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/budget-services:<image-version>
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: AWS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: DATABASE_URL
              value: <database-url>
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
