apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: transaction-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      name: transaction-service
      labels:
        app: transaction-service
    spec:
      serviceAccountName: transaction-service
      containers:
        - name: transaction-service
          image: 924809052459.dkr.ecr.us-east-1.amazonaws.com/transaction-service:<image-version>
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          env:
            - name: AWS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_URL
              value: http://discovery-service:8761/eureka
            - name: DATABASE_URL
              value: <database-url>
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
